[server]
headless = true
runOnSave = true

[client]
showSidebarNavigation = false

[theme]
primaryColor = "#EA9216"
backgroundColor = "#F6F6F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#313841"
font = "sans serif"
